### ISSUE TITLE
多拦截器下ParameterInterceptor异常

### ISSUE THREAD

**Issue by shangjianan2** [lmx1989219/common-util#5]
如果由多个拦截器使用了"type = ParameterHandler.class, method = "setParameters""并配置在ParameterInterceptor后面，ParameterInterceptor无法正常解析出parameterObject

Caused by: java.lang.NoSuchFieldException: parameterObject

`
ParameterHandler parameterHandler = (ParameterHandler) invocation.getTarget();
        Field parameterField = parameterHandler.getClass().getDeclaredField("parameterObject");// 此处报错
        parameterField.setAccessible(true);
`

参考[pageHelper](https://github.com/pagehelper/Mybatis-PageHelper)这个插件，我觉得可以在Executor而不是ParameterHandler中对入参进行处理

**Comment by lmx1989219** [comment]
拿出你的解决方案。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lmx1989219/common-util] 多拦截器下ParameterInterceptor异常 (Issue #5)




 
如果由多个拦截器配置在ParameterInterceptor后面配置了type = ParameterHandler.class, method = "setParameters"，ParameterInterceptor无法正常解析出parameterObject
 
Caused by: java.lang.NoSuchFieldException: parameterObject
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lmx1989219** [comment]
@shangjianan2 试试它。

`/**
 * 实体字段加解密拦截器
 * <p>
 * Created by lucas on 2020/7/8.
 */
@Intercepts({@Signature(type = Executor.class, method = "update", args = {MappedStatement.class, Object.class})
  , @Signature(type = Executor.class, method = "query", args = {MappedStatement.class, Object.class, RowBounds.class, ResultHandler.class})})
public class EncAndDecryptInterceptor implements Interceptor {
  private static final String NAME_ENTITY = "et", NATIVE_SQL_ENTITY_PREFIX = "param", NATIVE_SQL_ENTITY = "param1";
  private final Map<Class<?>, List<Field>> encFieldCache = new ConcurrentHashMap<>();
  private EncAndDecryptService encAndDecryptService;

  public EncAndDecryptInterceptor(EncAndDecryptService encAndDecryptService) {
    this.encAndDecryptService = encAndDecryptService;
  }

  public EncAndDecryptInterceptor() {
    this.encAndDecryptService = new DefaultAesServiceImpl();
  }

  @AllArgsConstructor
  class EncField {
    String paramName;
    int idx;
  }

  @Override
  @SuppressWarnings("unchecked")
  public Object intercept(Invocation invocation) throws Throwable {
    Object[] args = invocation.getArgs();
    Object param = args[1];
    MappedStatement mappedStatement = (MappedStatement) args[0];

    Method originMethod = getMethod(mappedStatement.getId());
    List<EncField> needEncList = Lists.newArrayList();
    int i = 0;
    for (Parameter parameter : originMethod.getParameters()) {
      EncDecrypt encDecrypt = parameter.getDeclaredAnnotation(EncDecrypt.class);
      Param param1 = parameter.getDeclaredAnnotation(Param.class);
      if (Objects.nonNull(encDecrypt)) {
        needEncList.add(new EncField(param1.value(), (i++) + 1));
      }
    }

    // entity = et
    Object et = null;
    //处理@Param注解的参数
    if (param instanceof Map) {
      Map map = (Map) param;
      if (map.containsKey(NAME_ENTITY)) {
        et = map.get(NAME_ENTITY);
      }
      if (map.containsKey(NATIVE_SQL_ENTITY)) {
        // non wrapper;
        et = map.get(NATIVE_SQL_ENTITY);
      }
      if (Objects.nonNull(et)) {
        if (invocation.getMethod().getName().equals("update")) {
          handlerEnc(et);
          return invocation.proceed();
        }
        if (invocation.getMethod().getName().equals("query")) {
          if (!needEncList.isEmpty()) {
            for (EncField encField : needEncList) {
              String key = NATIVE_SQL_ENTITY_PREFIX + encField.idx;
              et = ((Map) param).get(key);
              if (et instanceof String) {
                map.put(encField.paramName, encryptField(et));
                map.put(key, encryptField(et));
              }
            }
          } else {
            //查询参数明文转换为密文
            handlerEnc(et);
          }
          //解密
          Object resp = invocation.proceed();
          return handlerDecrypt(resp);
        }
      }
    } else {//无param注解参数的处理
      if (invocation.getMethod().getName().equals("update")) {
        handlerEnc(param);
        return invocation.proceed();
      }
      if (invocation.getMethod().getName().equals("query")) {
        //查询参数明文转换为密文
        handlerEnc(param);
        //解密
        Object resp = invocation.proceed();
        return handlerDecrypt(resp);
      }
    }
    return invocation.proceed();
  }

  private void handlerEnc(Object param) throws Exception {
    if (Objects.isNull(param)) return;
    Class<?> entityClass = param.getClass();

    List<Field> encDecryptField = this.getEncDecryptField(entityClass);
    if (CollectionUtils.isEmpty(encDecryptField)) {
      return;
    }
    for (Field field : encDecryptField) {
      field.setAccessible(true);
      Object originalVal = field.get(param);
      Object encryptVal = encryptField(originalVal);
      if (originalVal != null) {
        //加密
        field.set(param, encryptVal);
      }
    }
  }

  private Object handlerDecrypt(Object resp) throws Exception {
    if (resp instanceof List) {
      List<Object> resultList = ((List) resp);
      if (!CollectionUtils.isEmpty(resultList)) {
        for (Object entity : resultList) {
          if (Objects.nonNull(entity)) {
            Field[] fields = entity.getClass().getDeclaredFields();
            if (Objects.nonNull(fields)) {
              for (Field field : fields) {
                if (Objects.nonNull(field.getDeclaredAnnotation(EncDecrypt.class))) {
                  field.setAccessible(true);
                  Object enc = field.get(entity);
                  if (Objects.nonNull(enc))
                    field.set(entity, decryptField(enc));
                }
              }
            }
          }
        }
      }
    }
    return resp;
  }

  /**
   * 获取mapper定义的方法
   *
   * @return Method
   */
  private Method getMethod(String statementId) throws ClassNotFoundException {
    final Class clazz = Class.forName(statementId.substring(0, statementId.lastIndexOf(".")));
    final String methodName = statementId.substring(statementId.lastIndexOf(".") + 1);
    for (Method method : clazz.getMethods()) {
      if (method.getName().equals(methodName)) {
        return method;
      }
    }
    return null;
  }

  private Object encryptField(Object originalEncDecryptVal) throws Exception {
    return encAndDecryptService.encrypt(String.valueOf(originalEncDecryptVal));
  }

  private Object decryptField(Object originalEncDecryptVal) throws Exception {
    return encAndDecryptService.decrypt(String.valueOf(originalEncDecryptVal));
  }


  @Override
  public Object plugin(Object target) {
    if (target instanceof Executor) {
      return Plugin.wrap(target, this);
    }
    return target;
  }

  @Override
  public void setProperties(Properties properties) {
    // to do nothing
  }

  private List<Field> getEncDecryptField(Class<?> parameterClass) {
    try {
      synchronized (parameterClass.getName()) {
        if (encFieldCache.containsKey(parameterClass)) {
          return encFieldCache.get(parameterClass);
        }
        // 缓存类信息
        List<Field> fields = Lists.newArrayList(parameterClass.getDeclaredFields())
          .stream().filter(field -> Objects.nonNull(field.getDeclaredAnnotation(EncDecrypt.class))).collect(Collectors.toList());
        if (!fields.isEmpty()) {
          encFieldCache.put(parameterClass, fields);
          return fields;
        }
        return null;
      }
    } catch (Exception e) {
      return null;
    }
  }

}`



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [lmx1989219/common-util] 多拦截器下ParameterInterceptor异常 (Issue #5)




 
如果由多个拦截器配置在ParameterInterceptor后面配置了type = ParameterHandler.class, method = "setParameters"，ParameterInterceptor无法正常解析出parameterObject
 
Caused by: java.lang.NoSuchFieldException: parameterObject
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
